name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 7 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish Windows artifacts
        run: dotnet publish --runtime win-x64 --self-contained false --output build
      - name: Test
        run: zip --help
      - name: Archive 'build' folder
        run: zip -9 -r build.zip build
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          release_name: Release ${{ github.run_id }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build.zip
          asset_name: HelperTools.windows-amd64.zip
          asset_content_type: application/zip
